
import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: 'sembako',
    name: 'Sembako',
    image: '/placeholder.svg',
  },
  {
    id: 'air-minum',
    name: 'Air Minum',
    image: '/placeholder.svg',
  },
  {
    id: 'rokok',
    name: 'Rokok',
    image: '/placeholder.svg',
  },
  {
    id: 'mie-instan',
    name: 'Mie Instan',
    image: '/placeholder.svg',
  },
  {
    id: 'beras',
    name: 'Beras',
    image: '/placeholder.svg',
  },
  {
    id: 'obat-obatan',
    name: 'Obat-obatan',
    image: '/placeholder.svg',
  },
  {
    id: 'kosmetik',
    name: 'Kosmetik',
    image: '/placeholder.svg',
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Indomie Goreng',
    price: 3500,
    image: '/placeholder.svg',
    category: 'mie-instan',
    stock: 100,
    description: 'Mie instan goreng terlaris di Indonesia. Mudah disiapkan dan lezat.',
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Beras Ramos 5kg',
    price: 70000,
    discountPrice: 65000,
    image: '/placeholder.svg',
    category: 'beras',
    stock: 30,
    description: 'Beras premium kualitas terbaik. Beras putih bersih tanpa campuran.',
    isPromo: true,
  },
  {
    id: '3',
    name: 'Aqua 1.5L',
    price: 7000,
    image: '/placeholder.svg',
    category: 'air-minum',
    stock: 50,
    description: 'Air mineral berkualitas dalam kemasan botol 1.5 liter.',
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Rokok Gudang Garam Filter',
    price: 25000,
    image: '/placeholder.svg',
    category: 'rokok',
    stock: 40,
    description: 'Rokok kretek filter dengan tembakau pilihan. Isi 12 batang per pack.',
  },
  {
    id: '5',
    name: 'Paracetamol 500mg',
    price: 12000,
    image: '/placeholder.svg',
    category: 'obat-obatan',
    stock: 25,
    description: 'Obat pereda demam dan nyeri. Isi 10 tablet per strip.',
    isFeatured: true,
  },
  {
    id: '6',
    name: 'Sabun Lifebuoy',
    price: 5000,
    image: '/placeholder.svg',
    category: 'sembako',
    stock: 60,
    description: 'Sabun antiseptik yang efektif membunuh kuman. Isi 85gr per batang.',
  },
  {
    id: '7',
    name: 'Minyak Goreng Bimoli 1L',
    price: 25000,
    discountPrice: 22000,
    image: '/placeholder.svg',
    category: 'sembako',
    stock: 45,
    description: 'Minyak goreng jernih dari kelapa sawit pilihan. Kemasan 1 liter.',
    isPromo: true,
  },
  {
    id: '8',
    name: 'Gula Pasir 1kg',
    price: 15000,
    image: '/placeholder.svg',
    category: 'sembako',
    stock: 55,
    description: 'Gula pasir putih berkualitas. Kemasan 1kg.',
  },
  {
    id: '9',
    name: 'Mie Sedaap Goreng',
    price: 3200,
    image: '/placeholder.svg',
    category: 'mie-instan',
    stock: 80,
    description: 'Mie instan goreng dengan bumbu khas. Mudah disajikan.',
  },
  {
    id: '10',
    name: 'Le Minerale 600ml',
    price: 5000,
    image: '/placeholder.svg',
    category: 'air-minum',
    stock: 70,
    description: 'Air mineral dalam kemasan botol 600ml.',
  },
  {
    id: '11',
    name: 'Pond\'s White Beauty Cream',
    price: 30000,
    image: '/placeholder.svg',
    category: 'kosmetik',
    stock: 20,
    description: 'Krim pencerah wajah untuk kulit lebih cerah dan bercahaya.',
    isFeatured: true,
  },
  {
    id: '12',
    name: 'Sampoerna Mild',
    price: 28000,
    image: '/placeholder.svg',
    category: 'rokok',
    stock: 35,
    description: 'Rokok mild dengan nikotin rendah. Isi 16 batang per pack.',
  },
];
